config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  post 'github_webhook_pull_request', to: 'github_hooks#pull_request'

  root 'landing#home'

  # authenticate :user, ->(u) { u.superuser? } do
    mount Sidekiq::Web => '/sidekiq'
  # end

  resources :votes, only: [:create]

  get 'reviews/:repository/:sha', to: 'reviews#show'

  get 'content_instructions', to: redirect('https://github.com/convinceme/info/blob/master/content_guidelines.markdown')

  get 'not_found', to: 'errors#not_found'
  match '/404', to: 'errors#not_found', via: :all

  resources :debates, only: [:show, :edit, :update]
  get '*id', to: redirect('/debates/%{id}')
end

app/controllers/debates_controller.rb
# frozen_string_literal: true

class DebatesController < ApplicationController
  before_action :find_topic

  def show
    @title = @topic.name
    @display_char_count = ActiveRecord::Type::Boolean.new.cast(params[:count])
  end

  def edit
    @argument ||= @topic.arguments.where(perspective_id: perspective.id).first_or_initialize
  end

  def update
  end

  helper_method :perspective

  private

  def find_topic
    @topic = Topic.friendly_find(params[:id])
    return @topic if @topic.present?
    render(not_found_path, status: 404)
    return
  end

  def perspective
    @perspective ||= params[:perspective] == 'con' ? Perspective.con : Perspective.pro
  end
end

app/views/debates/edit.html.haml
.editing-debate.container-fluid
  %header
    %h1
      Editing Argument
      %strong
        = perspective.pro? ? 'For' : 'Against'
      %em
        = @topic.name
  = form_tag debate_path(@topic.slug, perspective: @perspective.slug), method: :put do
    .row
      - if @argument && @argument.body_html
        .col-sm-6
          .argument
            .content-inner
              - if @argument && @argument.body_html
                = @argument.body_html.html_safe
      - else
        .col-sm-3
      .col-sm-6.argument-body-form
        = text_area_tag :body, @argument.body_html, rows: 3, class: 'form-control'
    .row.mt-2
      .col-sm-6.col-md-3.offset-6.offset-md-9.submit-suggestion
        = submit_tag 'Suggest update', class: 'btn btn-primary'
    .row.mt-4.references-title
      .col-6
        %h2
          References
      .col-6.text-right
        %a.add-additional-reference.collapse{ href: '#' }
          Add a new reference

    .row.references-form-fields.mt-2
      - ([@argument.empty_reference] + @argument.references).each_with_index do |reference, i|
        .col-md-6.individual-reference{ class: ('emptyRef' if i == 0) }
          .row
            .col-6
              = label_tag "reference_#{i}_title", 'Title'
              = text_field_tag "reference_#{i}_title", reference[:title], class: 'form-control'
            .col-6.col-lg-4
              = label_tag "reference_#{i}_author", 'Author'
              = text_field_tag "reference_#{i}_author", reference[:author], class: 'form-control'
            .col-lg-6.order-2
              = label_tag "reference_#{i}_link", 'Link'
              = text_field_tag "reference_#{i}_link", reference[:link], class: 'form-control'
            .col-lg-6.col-8.order-3
              = label_tag "reference_#{i}_publisher", 'Publisher'
              = text_field_tag "reference_#{i}_publisher", reference[:publisher], class: 'form-control'
            .col-lg-2.col-4.order-4.order-lg-1
              = label_tag "reference_#{i}_date_published", 'Published'
              = text_field_tag "reference_#{i}_date_published", reference[:date_published], class: 'form-control'

app/views/debates/show.html.haml
%header.title
  %h1
    = @topic.name
.clearfix
  - cache @topic do
    - @topic.perspective_hashes.each do |persp_hash|
      - argument = persp_hash[:argument_id] && @topic.arguments.find(persp_hash[:argument_id])
      .argument
        .content-inner
          - if argument && argument.body_html
            = argument.body_html.html_safe
            %span.argument-enumerator
              = persp_hash[:enum_letter]
            .link-to-pr
              = link_to "Improve this argument (actual link)", edit_debate_path(@topic.to_param, perspective: perspective.slug)
          - else
            - perspective = Perspective.find(persp_hash[:perspective_id])
            .link-to-pr
              = link_to "Write the #{perspective.name.downcase}", edit_debate_path(@topic.to_param, perspective: perspective.slug)

%section.voting-section
  - if !current_user || current_user.can_vote?(kind: 'quality', topic: @topic)
    .voting-text
      / ^ Can't be a %p, because inline and it has a form in it
      Which is better argued: #{ argument_links(@topic.perspective_hashes, kind: 'quality') }
  - if !current_user || current_user.can_vote?(kind: 'opinion', topic: @topic)
    .voting-text
      Which do you agree with more: #{ argument_links(@topic.perspective_hashes, kind: 'opinion') }

%section.related-topics
  - if @topic.child_topics.present?
    %h4
      More specific topics the government could make:
    %ul
      - @topic.child_topics.each do |child_topic|
        %li
          = link_to child_topic.name, "/#{child_topic.slug}"
  - if @topic.parent_topic.present?
    %h4
      More general topic the government could make:
    %ul
      %li
        = link_to @topic.parent_topic.name, "/#{@topic.parent_change.slug}"